#!/bin/bash
source ./common/configs/.shell-functions

cp ./common/configs/.gitignore_global ~/.gitignore_global
cp ./common/configs/.tmux.conf ~/.tmux.conf
cp ./common/configs/.bashrc ~/.bashrc
cp ./common/configs/.zshrc ~/.zshrc

> ~/.shrc
appendIfMissing ./common/configs/.shrc.aliases ~/.shrc
appendIfMissing ./common/configs/.shrc.keys ~/.shrc
appendIfMissing ./common/configs/.shrc.gopath ~/.shrc

if [[ "$(uname)" == 'Darwin' ]]; then
    appendIfMissing ./common/configs/.shrc.aliases ~/.pipo
    appendIfMissing ./osx/configs/.shrc.aliases ~/.shrc
    appendIfMissing ./osx/configs/.shrc.docker ~/.shrc
    appendIfMissing ./osx/configs/.shrc.tmux ~/.shrc
    appendIfMissing ./osx/configs/.shrc.typeform ~/.shrc
elif [[ "$(uname)" == 'Linux' ]]; then
    echo 'Linux'
fi