#!/bin/bash
[[ -z $repo ]] && repo=$(cd $(dirname $BASH_SOURCE[0]) && cd .. && pwd)

. "${repo}"/configs/shell-functions.sh
> ~/.shrc

appendIfMissing "${repo}"/configs/.gitignore_global ~/.gitignore_global
appendIfMissing "${repo}"/configs/.bashrc ~/.bashrc
appendIfMissing "${repo}"/configs/.zshrc ~/.zshrc

appendIfMissing "${repo}"/configs/shell-functions.sh ~/.shrc
appendIfMissing "${repo}"/configs/.shrc.aliases ~/.shrc
appendIfMissing "${repo}"/configs/.shrc.keys ~/.shrc
appendIfMissing "${repo}"/configs/.shrc.gopath ~/.shrc

if [[ "$(uname)" == 'Darwin' ]]; then
    appendIfMissing "${repo}"/configs/osx/.shrc.aliases ~/.shrc
    appendIfMissing "${repo}"/configs/osx/.shrc.docker ~/.shrc
    appendIfMissing "${repo}"/configs/osx/.shrc.typeform ~/.shrc
    appendIfMissing "${repo}"/configs/osx/.bash_profile ~/.bash_profile
elif [[ "$(uname)" == 'Linux' ]]; then
    appendIfMissing "${repo}"/configs/ubuntu/.shrc.aliases ~/.shrc
    appendIfMissing "${repo}"/configs/ubuntu/.xbindkeysrc ~/.xbindkeysrc
    appendIfMissing "${repo}"/configs/ubuntu/.xmodmap ~/.xmodmap
    appendIfMissing "${repo}"/configs/ubuntu/shell-functions.sh ~/.shrc
fi